import argparse
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from tqdm import tqdm


DEFAULT_BASE_URL = "http://127.0.0.1:1234/v1"
DEFAULT_LANGUAGE = "Simplified Chinese"
DEFAULT_MODEL = "auto"
DEFAULT_BATCH = 8
DEFAULT_CONTEXT = 4
DEFAULT_TIMEOUT = 120
DEFAULT_RETRIES = 3
DEFAULT_TEMPERATURE = 0.7
DEFAULT_TOP_P = 0.6
DEFAULT_MAX_TOKENS = 2048

# Ren'Py text tags/interpolation, escaped sequences and printf-style placeholders.
# These tokens must never be translated or modified.
PROTECTED_TOKEN_RE = re.compile(
    r"(\{/?[A-Za-z][^{}]*\}|\[[^\[\]\n]+\]|%(?:\([^)]+\))?[#0\- +]?(?:\d+|\*)?(?:\.\d+|\.\*)?[diouxXeEfFgGcrs%]|\\[nrt\"\\])"
)

# Translation-template string lines such as:
#     "Hello"
#     e "Hello"
#     old "Hello"
#     new "Hello"
QUOTED_RE = re.compile(
    r'^(?P<prefix>\s*(?:old\s+|new\s+|[A-Za-z_][\w.]*\s+)?)"(?P<text>(?:\\.|[^"\\])*)"(?P<suffix>\s*)$'
)

# Generated Ren'Py dialogue translations normally retain the English source as a
# commented line immediately above the editable target line.
COMMENTED_QUOTED_RE = re.compile(
    r'^\s*#\s*(?P<prefix>(?:[A-Za-z_][\w.]*\s+)?)"(?P<text>(?:\\.|[^"\\])*)"\s*$'
)

CJK_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff]")
LATIN_RE = re.compile(r"[A-Za-z]")
BATCH_MARKER_RE = re.compile(r"(?m)^<<<RET_(\d{4})>>>\s*")


def http_json(method, url, payload=None, timeout=DEFAULT_TIMEOUT):
    data = None
    headers = {"Content-Type": "application/json"}
    if payload is not None:
        data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {e.code}: {body}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"无法连接 LM Studio：{e}") from e


def normalize_base_url(url):
    url = url.rstrip("/")
    if url.endswith("/v1"):
        return url
    return url + "/v1"


def detect_model(base_url, requested):
    if requested and requested.lower() != "auto":
        return requested
    result = http_json("GET", f"{base_url}/models")
    models = result.get("data", [])
    if not models:
        raise RuntimeError(
            "LM Studio /v1/models 没有返回已加载模型，请先在 LM Studio 中加载模型并启动 Local Server。"
        )
    return models[0]["id"]


def decode_renpy_string(text):
    # Deliberately conservative: unicode_escape would corrupt non-ASCII text.
    return text.replace(r'\"', '"').replace(r"\\", "\\")


def encode_renpy_string(text):
    return (
        text.replace("\\", r"\\")
        .replace('"', r'\"')
        .replace("\r", "")
        .replace("\n", r"\n")
    )


def recover_original_source(lines, idx, current_prefix):
    """Try to recover the English source for an already translated target line."""
    prefix_name = current_prefix.strip()

    # old/new string translation pair.
    if prefix_name == "new":
        for j in range(idx - 1, max(-1, idx - 8), -1):
            pm = QUOTED_RE.match(lines[j])
            if pm and pm.group("prefix").strip() == "old":
                return decode_renpy_string(pm.group("text"))

    # Dialogue/narration generated by Ren'Py keeps the original as a comment.
    expected_speaker = prefix_name
    for j in range(idx - 1, max(-1, idx - 8), -1):
        cm = COMMENTED_QUOTED_RE.match(lines[j])
        if not cm:
            continue
        speaker = cm.group("prefix").strip()
        if expected_speaker and speaker and speaker != expected_speaker:
            continue
        source = decode_renpy_string(cm.group("text"))
        if source.strip():
            return source

    return None


def collect_entries(lines, retranslate=False):
    entries = []
    for idx, line in enumerate(lines):
        if line.lstrip().startswith("#"):
            continue

        m = QUOTED_RE.match(line)
        if not m:
            continue

        prefix_name = m.group("prefix").strip()
        if prefix_name == "old":
            continue

        current_text = decode_renpy_string(m.group("text"))
        if not current_text.strip():
            continue

        source_text = current_text

        if prefix_name == "new":
            original = recover_original_source(lines, idx, m.group("prefix"))
            if original is not None:
                # If 'new' has already been changed, preserve it unless explicitly
                # retranslation was requested.
                if current_text != original and not retranslate:
                    continue
                source_text = original

        if CJK_RE.search(current_text):
            if not retranslate:
                # Default resume behaviour: existing Chinese is never touched.
                continue
            original = recover_original_source(lines, idx, m.group("prefix"))
            if original is None or not LATIN_RE.search(original):
                # We cannot safely retranslate without the original English source.
                continue
            source_text = original

        if not LATIN_RE.search(source_text):
            continue

        entries.append(
            {
                "line": idx,
                "prefix": m.group("prefix"),
                "suffix": m.group("suffix"),
                "text": source_text,
                "current": current_text,
            }
        )

    return entries


def make_placeholders(text, item_index=0):
    """Replace protected Ren'Py tokens with item-specific ASCII placeholders."""
    table = []

    def repl(match):
        marker = f"__RET_TAG_{item_index:02d}_{len(table):03d}__"
        table.append((marker, match.group(0)))
        return marker

    return PROTECTED_TOKEN_RE.sub(repl, text), table


def clean_model_output(content):
    content = str(content).strip()

    if content.startswith("```"):
        content = re.sub(r"^```(?:text|txt|json)?\s*", "", content, flags=re.I)
        content = re.sub(r"\s*```$", "", content)
        content = content.strip()

    content = re.sub(
        r"^(?:翻译(?:结果|如下)?|译文|简体中文|中文译文)\s*[:：]\s*",
        "",
        content,
        flags=re.I,
    ).strip()

    if len(content) >= 2 and content[0] == '"' and content[-1] == '"':
        try:
            decoded = json.loads(content)
            if isinstance(decoded, str):
                content = decoded
        except json.JSONDecodeError:
            pass

    return content.strip()


def api_chat(
    base_url,
    model,
    prompt,
    timeout,
    retries,
    temperature,
    top_p,
    max_tokens,
):
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": temperature,
        "top_p": top_p,
        "max_tokens": max_tokens,
        "stream": False,
    }

    last_error = None
    for attempt in range(1, retries + 1):
        try:
            result = http_json(
                "POST", f"{base_url}/chat/completions", payload, timeout=timeout
            )
            content = result["choices"][0]["message"]["content"]
            cleaned = clean_model_output(content)
            if not cleaned:
                raise ValueError("模型返回了空译文")
            return cleaned
        except Exception as e:
            last_error = e
            if attempt < retries:
                time.sleep(min(2 ** (attempt - 1), 5))

    raise RuntimeError(f"翻译失败，重试 {retries} 次后仍出错：{last_error}")


def translate_piece(base_url, model, piece, args):
    m = re.match(r"^(\s*)(.*?)(\s*)$", piece, flags=re.S)
    leading, core, trailing = m.groups()
    if not core or not LATIN_RE.search(core):
        return piece

    prompt = (
        f"将以下英文视觉小说文本翻译为{args.target_language}。"
        "只输出译文，不要解释，不要添加引号。"
        "保持人物语气、俚语、粗口、性暗示及虚构成人对白的原意，不要弱化措辞。\n\n"
        + core
    )
    translated = api_chat(
        base_url,
        model,
        prompt,
        args.timeout,
        args.retries,
        args.temperature,
        args.top_p,
        args.max_tokens,
    )
    return leading + translated + trailing


def translate_by_segments(base_url, model, text, args):
    """Guaranteed-safe fallback: protected tokens are never sent to the model."""
    parts = PROTECTED_TOKEN_RE.split(text)
    out = []
    for part in parts:
        if not part:
            continue
        if PROTECTED_TOKEN_RE.fullmatch(part):
            out.append(part)
        else:
            out.append(translate_piece(base_url, model, part, args))
    return "".join(out)


def translate_single(base_url, model, text, args, context=None):
    protected, table = make_placeholders(text, 0)

    context_text = ""
    if context:
        context_text = "\n以下是前文，仅用于理解人物关系和语气，不要翻译或输出前文：\n"
        for src, dst in context[-args.context :]:
            context_text += f"EN: {src}\nZH: {dst}\n"

    placeholder_note = ""
    if table:
        placeholder_note = (
            " 文本中的 __RET_TAG_00_000__ 这类标记必须逐字原样保留，"
            "不要删除、翻译、移动或改变。"
        )

    prompt = (
        f"将以下英文视觉小说文本翻译为{args.target_language}。"
        "只输出当前文本的译文，不要解释，不要添加引号。"
        "保持人物语气、俚语、粗口、性暗示及虚构成人对白的原意，不要弱化措辞。"
        + placeholder_note
        + context_text
        + "\n当前文本：\n"
        + protected
    )

    translated = api_chat(
        base_url,
        model,
        prompt,
        args.timeout,
        args.retries,
        args.temperature,
        args.top_p,
        args.max_tokens,
    )

    if table and not all(translated.count(marker) == 1 for marker, _ in table):
        return translate_by_segments(base_url, model, text, args)

    for marker, original in table:
        translated = translated.replace(marker, original)

    return translated


def build_batch_prompt(items, args, context):
    protected_items = []
    tables = []

    for i, item in enumerate(items):
        protected, table = make_placeholders(item["text"], i)
        protected_items.append(protected)
        tables.append(table)

    context_text = ""
    if context and args.context > 0:
        context_text = (
            "\n【前文参考】下面内容只用于理解上下文，不要输出这些内容：\n"
        )
        for src, dst in context[-args.context :]:
            context_text += f"EN: {src}\nZH: {dst}\n"

    current = []
    for i, text in enumerate(protected_items):
        current.append(f"<<<RET_{i:04d}>>>\n{text}")

    prompt = (
        f"把下面多条英文视觉小说文本翻译为{args.target_language}。"
        "这些文本按剧情顺序排列，可以互相作为上下文。"
        "保持人物语气、俚语、粗口、性暗示及虚构成人对白原意，不要弱化措辞。"
        "所有 __RET_TAG_XX_XXX__ 都是 Ren'Py 标签占位符，必须逐字原样保留。"
        "\n输出规则非常重要："
        "每条译文前必须原样输出对应的 <<<RET_0000>>> 标记；"
        "不要输出英文原文、解释、JSON、代码块或其他内容；"
        "不得合并、删除或重新排序条目。"
        + context_text
        + "\n【当前待翻译文本】\n"
        + "\n".join(current)
    )

    return prompt, tables


def parse_batch_response(content, count):
    content = clean_model_output(content)
    matches = list(BATCH_MARKER_RE.finditer(content))
    if len(matches) != count:
        raise ValueError(f"批量标记数量不匹配：期望 {count}，实际 {len(matches)}")

    result = {}
    for pos, match in enumerate(matches):
        idx = int(match.group(1))
        if idx < 0 or idx >= count or idx in result:
            raise ValueError(f"批量标记异常：RET_{idx:04d}")
        start = match.end()
        end = matches[pos + 1].start() if pos + 1 < len(matches) else len(content)
        result[idx] = content[start:end].strip()

    if set(result) != set(range(count)):
        raise ValueError("批量返回缺少或重复条目")
    if any(not result[i] for i in range(count)):
        raise ValueError("批量返回存在空译文")

    return [result[i] for i in range(count)]


def translate_batch(base_url, model, items, args, context):
    """
    Fast path: translate several consecutive VN lines in one API request.
    Any protocol/tag failure raises and the caller falls back to safe single-line mode.
    """
    if len(items) == 1:
        return [translate_single(base_url, model, items[0]["text"], args, context)]

    prompt, tables = build_batch_prompt(items, args, context)
    content = api_chat(
        base_url,
        model,
        prompt,
        args.timeout,
        args.retries,
        args.temperature,
        args.top_p,
        args.max_tokens,
    )
    outputs = parse_batch_response(content, len(items))

    restored = []
    for i, translated in enumerate(outputs):
        table = tables[i]
        if table and not all(translated.count(marker) == 1 for marker, _ in table):
            raise ValueError(f"第 {i + 1} 条的 Ren'Py 标签占位符未完整保留")
        for marker, original in table:
            translated = translated.replace(marker, original)
        restored.append(translated)

    return restored


def find_rpy_files(path):
    return sorted(Path(path).rglob("*.rpy"))


def load_finished(path):
    if not path.exists():
        return set()
    return {
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    }


def append_finished(path, file_path):
    with path.open("a", encoding="utf-8") as f:
        f.write(str(file_path.resolve()) + "\n")


def process_file(file_path, args, model, finished_path, finished):
    resolved = str(file_path.resolve())
    if resolved in finished and not args.retranslate:
        print(f"跳过已完成：{file_path}")
        return

    original = file_path.read_text(encoding="utf-8")
    lines = original.splitlines(keepends=False)
    entries = collect_entries(lines, retranslate=args.retranslate)
    if not entries:
        print(f"无待翻译文本，跳过：{file_path}")
        if not args.retranslate and resolved not in finished:
            append_finished(finished_path, file_path)
        return

    backup_path = file_path.with_suffix(file_path.suffix + ".bak")
    if args.backup and not backup_path.exists():
        backup_path.write_text(original, encoding="utf-8")

    history = []
    groups = range(0, len(entries), args.batch)
    for start in tqdm(groups, desc=file_path.name, unit="batch"):
        batch = entries[start : start + args.batch]

        try:
            results = translate_batch(args.base_url, model, batch, args, history)
        except Exception as batch_error:
            # HY-MT may occasionally ignore the multi-entry output protocol. Do not
            # fail the file: transparently retry this batch one line at a time.
            tqdm.write(f"批量翻译降级为单句：{batch_error}")
            results = []
            for entry in batch:
                translated = translate_single(
                    args.base_url, model, entry["text"], args, history
                )
                results.append(translated)
                history.append((entry["text"], translated))
        else:
            for entry, translated in zip(batch, results):
                history.append((entry["text"], translated))

        # Keep only the amount of history we actually need.
        if args.context >= 0 and len(history) > max(args.context, 1) * 2:
            history = history[-max(args.context, 1) * 2 :]

        for entry, translated in zip(batch, results):
            escaped = encode_renpy_string(translated)
            lines[entry["line"]] = (
                f'{entry["prefix"]}"{escaped}"{entry["suffix"]}'
            )

        # Incremental checkpoint so Ctrl+C or a model error does not lose progress.
        file_path.write_text(
            "\n".join(lines) + ("\n" if original.endswith("\n") else ""),
            encoding="utf-8",
        )

    if not args.retranslate:
        append_finished(finished_path, file_path)
    print(f"处理完成：{file_path}")


def parse_args():
    p = argparse.ArgumentParser(
        description="Ren'Py rpy 本地 AI 一键翻译（LM Studio / OpenAI Compatible API）"
    )
    p.add_argument(
        "path", help="Ren'Py 生成的翻译目录，例如 game/tl/schinese"
    )
    p.add_argument(
        "--base-url",
        default=os.getenv("LMSTUDIO_BASE_URL", DEFAULT_BASE_URL),
        help="LM Studio API，默认 http://127.0.0.1:1234/v1",
    )
    p.add_argument(
        "--model",
        default=os.getenv("LMSTUDIO_MODEL", DEFAULT_MODEL),
        help="模型 id；默认 auto 自动取 /v1/models 第一个模型",
    )
    p.add_argument("--target-language", default=DEFAULT_LANGUAGE)
    p.add_argument(
        "--batch",
        type=int,
        default=DEFAULT_BATCH,
        help="每个 API 请求尝试翻译的连续文本条数，默认 8；失败会自动降级单句",
    )
    p.add_argument(
        "--context",
        type=int,
        default=DEFAULT_CONTEXT,
        help="附带前文的已翻译对话条数，默认 4；0 为关闭",
    )
    p.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT)
    p.add_argument("--retries", type=int, default=DEFAULT_RETRIES)
    p.add_argument("--temperature", type=float, default=DEFAULT_TEMPERATURE)
    p.add_argument("--top-p", type=float, default=DEFAULT_TOP_P)
    p.add_argument("--max-tokens", type=int, default=DEFAULT_MAX_TOKENS)
    p.add_argument(
        "--retranslate",
        action="store_true",
        help="重新翻译已经是中文的行；会尝试从 Ren'Py 注释/old 行恢复英文原文",
    )
    p.add_argument(
        "--no-backup",
        dest="backup",
        action="store_false",
        help="不创建 .rpy.bak 备份",
    )
    p.set_defaults(backup=True)
    return p.parse_args()


def main():
    args = parse_args()
    if args.batch < 1:
        print("--batch 必须 >= 1", file=sys.stderr)
        return 2
    if args.context < 0:
        print("--context 必须 >= 0", file=sys.stderr)
        return 2

    args.base_url = normalize_base_url(args.base_url)
    root = Path(args.path)
    if not root.exists():
        print(f"目录不存在：{root}", file=sys.stderr)
        return 2

    model = detect_model(args.base_url, args.model)
    print(f"LM Studio: {args.base_url}")
    print(f"模型: {model}")
    print(f"翻译目录: {root.resolve()}")
    print(f"批量: {args.batch} 条/请求；前文上下文: {args.context} 条")
    if args.retranslate:
        print("模式: 重新翻译已有中文（仅能恢复到英文原文的行）")
    else:
        print("模式: 增量翻译（已有中文保持不变）")

    finished_path = Path("finished_file_list_lmstudio.txt")
    finished = load_finished(finished_path)
    files = find_rpy_files(root)
    if not files:
        print("没有找到 .rpy 文件。")
        return 1

    for file_path in files:
        try:
            process_file(file_path, args, model, finished_path, finished)
        except KeyboardInterrupt:
            print("\n用户中止。已完成的批次已写回文件。")
            return 130
        except Exception as e:
            with Path("error_file_list_lmstudio.txt").open(
                "a", encoding="utf-8"
            ) as f:
                f.write(f"{file_path.resolve()}\t{e}\n")
            print(f"处理失败：{file_path}\n{e}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
