import argparse
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from tqdm import tqdm


DEFAULT_BASE_URL = "http://127.0.0.1:1234/v1"
DEFAULT_LANGUAGE = "Simplified Chinese"
DEFAULT_MODEL = "auto"

# HY-MT is much faster when several plain dialogue lines are translated in one request.
# 16 is intentionally conservative; 24/32 can be faster on a stable local setup.
DEFAULT_BATCH = 16
DEFAULT_CONTEXT = 0
DEFAULT_MAX_BATCH_CHARS = 6000

DEFAULT_TIMEOUT = 120
DEFAULT_RETRIES = 2
DEFAULT_TEMPERATURE = 0.7
DEFAULT_TOP_P = 0.6
DEFAULT_MAX_TOKENS = 2048

# Ren'Py text tags/interpolation, escaped sequences and printf-style placeholders.
# Lines containing these tokens are NOT sent through the multiline fast path. Instead
# the code splits around the tokens, translates only ordinary text, and rejoins them.
# This means the model never has to reproduce {i}, {/i}, [player_name], %(name)s, etc.
PROTECTED_TOKEN_RE = re.compile(
    r"(\{/?[A-Za-z][^{}]*\}|\[[^\[\]\n]+\]|%(?:\([^)]+\))?[#0\- +]?(?:\d+|\*)?(?:\.\d+|\.\*)?[diouxXeEfFgGcrs%]|\\[nrt\"\\])"
)

# Translation-template string lines such as:
#     "Hello"
#     e "Hello"
#     old "Hello"
#     new "Hello"
QUOTED_RE = re.compile(
    r'^(?P<prefix>\s*(?:old\s+|new\s+|[A-Za-z_][\w.]*\s+)?)"(?P<text>(?:\\.|[^"\\])*)"(?P<suffix>\s*)$'
)

# Generated Ren'Py dialogue translations normally retain the English source as a
# commented line immediately above the editable target line.
COMMENTED_QUOTED_RE = re.compile(
    r'^\s*#\s*(?P<prefix>(?:[A-Za-z_][\w.]*\s+)?)"(?P<text>(?:\\.|[^"\\])*)"\s*$'
)

CJK_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff]")
LATIN_RE = re.compile(r"[A-Za-z]")
NUMBER_PREFIX_RE = re.compile(r"^\s*(?:\d+[\.\)、:：]\s*|[-*]\s+)")


def http_json(method, url, payload=None, timeout=DEFAULT_TIMEOUT):
    data = None
    headers = {"Content-Type": "application/json"}
    if payload is not None:
        data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {e.code}: {body}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"无法连接 LM Studio：{e}") from e


def normalize_base_url(url):
    url = url.rstrip("/")
    if url.endswith("/v1"):
        return url
    return url + "/v1"


def detect_model(base_url, requested):
    if requested and requested.lower() != "auto":
        return requested
    result = http_json("GET", f"{base_url}/models")
    models = result.get("data", [])
    if not models:
        raise RuntimeError(
            "LM Studio /v1/models 没有返回已加载模型，请先在 LM Studio 中加载模型并启动 Local Server。"
        )
    return models[0]["id"]


def decode_renpy_string(text):
    # Deliberately conservative: unicode_escape would corrupt non-ASCII text.
    return text.replace(r'\"', '"').replace(r"\\", "\\")


def encode_renpy_string(text):
    return (
        text.replace("\\", r"\\")
        .replace('"', r'\"')
        .replace("\r", "")
        .replace("\n", r"\n")
    )


def recover_original_source(lines, idx, current_prefix):
    """Try to recover the English source for an already translated target line."""
    prefix_name = current_prefix.strip()

    # old/new string translation pair.
    if prefix_name == "new":
        for j in range(idx - 1, max(-1, idx - 8), -1):
            pm = QUOTED_RE.match(lines[j])
            if pm and pm.group("prefix").strip() == "old":
                return decode_renpy_string(pm.group("text"))

    # Dialogue/narration generated by Ren'Py keeps the original as a comment.
    expected_speaker = prefix_name
    for j in range(idx - 1, max(-1, idx - 8), -1):
        cm = COMMENTED_QUOTED_RE.match(lines[j])
        if not cm:
            continue
        speaker = cm.group("prefix").strip()
        if expected_speaker and speaker and speaker != expected_speaker:
            continue
        source = decode_renpy_string(cm.group("text"))
        if source.strip():
            return source

    return None


def collect_entries(lines, retranslate=False):
    entries = []

    for idx, line in enumerate(lines):
        if line.lstrip().startswith("#"):
            continue

        m = QUOTED_RE.match(line)
        if not m:
            continue

        prefix_name = m.group("prefix").strip()
        if prefix_name == "old":
            continue

        current_text = decode_renpy_string(m.group("text"))
        if not current_text.strip():
            continue

        source_text = current_text

        if prefix_name == "new":
            original = recover_original_source(lines, idx, m.group("prefix"))
            if original is not None:
                # If 'new' has already been changed, preserve it unless explicit
                # retranslation was requested.
                if current_text != original and not retranslate:
                    continue
                source_text = original

        if CJK_RE.search(current_text):
            if not retranslate:
                # Resume-safe default: existing Chinese is never changed.
                continue
            original = recover_original_source(lines, idx, m.group("prefix"))
            if original is None or not LATIN_RE.search(original):
                continue
            source_text = original

        if not LATIN_RE.search(source_text):
            continue

        entries.append(
            {
                "line": idx,
                "prefix": m.group("prefix"),
                "suffix": m.group("suffix"),
                "text": source_text,
                "current": current_text,
            }
        )

    return entries


def clean_model_output(content):
    content = str(content).strip()

    if content.startswith("```"):
        content = re.sub(r"^```(?:text|txt|json)?\s*", "", content, flags=re.I)
        content = re.sub(r"\s*```$", "", content)
        content = content.strip()

    content = re.sub(
        r"^(?:翻译(?:结果|如下)?|译文|简体中文|中文译文)\s*[:：]\s*",
        "",
        content,
        flags=re.I,
    ).strip()

    if len(content) >= 2 and content[0] == '"' and content[-1] == '"':
        try:
            decoded = json.loads(content)
            if isinstance(decoded, str):
                content = decoded
        except json.JSONDecodeError:
            pass

    return content.strip()


def api_chat(base_url, model, prompt, args):
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": args.temperature,
        "top_p": args.top_p,
        "max_tokens": args.max_tokens,
        "stream": False,
    }

    last_error = None
    for attempt in range(1, args.retries + 1):
        try:
            result = http_json(
                "POST",
                f"{base_url}/chat/completions",
                payload,
                timeout=args.timeout,
            )
            content = result["choices"][0]["message"]["content"]
            cleaned = clean_model_output(content)
            if not cleaned:
                raise ValueError("模型返回了空译文")
            return cleaned
        except Exception as e:
            last_error = e
            if attempt < args.retries:
                time.sleep(min(2 ** (attempt - 1), 3))

    raise RuntimeError(f"翻译失败，重试 {args.retries} 次后仍出错：{last_error}")


def context_prompt(context, args):
    if not context or args.context <= 0:
        return ""

    rows = context[-args.context :]
    text = "以下是前文参考，仅用于理解人物关系和语气，不要输出或重新翻译前文：\n"
    for src, dst in rows:
        text += f"EN: {src}\nZH: {dst}\n"
    return text + "\n"


def translate_plain_single(base_url, model, text, args, context=None):
    prompt = (
        context_prompt(context, args)
        + f"将以下英文视觉小说文本翻译为{args.target_language}。"
        "只输出译文，不要解释，不要添加引号。"
        "保持人物语气、俚语、粗口、性暗示及虚构成人对白原意，不要弱化措辞。\n\n"
        + text
    )
    return api_chat(base_url, model, prompt, args)


def translate_protected(base_url, model, text, args, context=None):
    """
    Safe path for lines containing Ren'Py tags/variables.

    Protected tokens are never sent to the model. Ordinary text segments around them
    are translated independently and then joined with the original tokens. This is a
    little slower for tagged lines, but it eliminates the old {i}/{/i} loss problem.
    """
    parts = PROTECTED_TOKEN_RE.split(text)
    out = []

    for part in parts:
        if not part:
            continue
        if PROTECTED_TOKEN_RE.fullmatch(part):
            out.append(part)
            continue

        m = re.match(r"^(\s*)(.*?)(\s*)$", part, flags=re.S)
        leading, core, trailing = m.groups()
        if not core or not LATIN_RE.search(core):
            out.append(part)
            continue

        translated = translate_plain_single(base_url, model, core, args, context)
        out.append(leading + translated + trailing)

    return "".join(out)


def normalize_multiline_output(content, expected_count):
    """
    HY-MT generally preserves line breaks much better than synthetic markers/JSON.
    Accept exactly one translated line per source line. A small numbered-prefix
    cleanup is allowed because some chat templates may add 1./2. despite prompting.
    """
    content = clean_model_output(content)
    lines = content.splitlines()

    # Remove only leading/trailing blank lines, never blanks in the middle.
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()

    if len(lines) != expected_count:
        raise ValueError(
            f"批量译文行数不匹配：期望 {expected_count}，实际 {len(lines)}"
        )

    cleaned = []
    for line in lines:
        line = NUMBER_PREFIX_RE.sub("", line).strip()
        if not line:
            raise ValueError("批量译文存在空行")
        cleaned.append(line)

    return cleaned


def translate_plain_batch_once(base_url, model, items, args, context=None):
    """
    Fast HY-MT path.

    No JSON, no RET markers and no Ren'Py tags are included. We simply send N plain
    dialogue lines and require N translated lines back. Consecutive lines naturally
    provide each other with local VN context.
    """
    if len(items) == 1:
        return [
            translate_plain_single(
                base_url, model, items[0]["text"], args, context
            )
        ]

    source_lines = [item["text"].replace("\r", " ").replace("\n", " ") for item in items]
    prompt = (
        context_prompt(context, args)
        + f"将下面 {len(items)} 行英文视觉小说对白/旁白逐行翻译为{args.target_language}。"
        f"输出必须恰好 {len(items)} 行，一行对应一行，顺序完全一致。"
        "不要编号，不要解释，不要输出英文原文，不要合并或拆分行。"
        "保持人物语气、俚语、粗口、性暗示及虚构成人对白原意，不要弱化措辞。\n\n"
        + "\n".join(source_lines)
    )

    content = api_chat(base_url, model, prompt, args)
    return normalize_multiline_output(content, len(items))


def translate_plain_batch_recursive(base_url, model, items, args, context=None, depth=0):
    """
    Translate a plain-text batch. On a formatting failure, split the batch in half
    instead of immediately falling back to N single requests.

    Example: 16 -> 8+8 -> only the troublesome half may become 4+4/2+2/1.
    This is substantially faster than the previous all-or-nothing fallback.
    """
    try:
        return translate_plain_batch_once(base_url, model, items, args, context)
    except Exception as e:
        if len(items) == 1:
            raise

        mid = len(items) // 2
        if depth == 0:
            tqdm.write(
                f"批量格式不稳定，自动二分重试：{len(items)} -> "
                f"{mid}+{len(items) - mid}（{e}）"
            )

        left = translate_plain_batch_recursive(
            base_url, model, items[:mid], args, context, depth + 1
        )

        # Let the successfully translated left half become context for the right half.
        right_context = list(context or [])
        for item, translated in zip(items[:mid], left):
            right_context.append((item["text"], translated))

        right = translate_plain_batch_recursive(
            base_url, model, items[mid:], args, right_context, depth + 1
        )
        return left + right


def is_fast_safe(text):
    # Any protected token or real newline goes through the safe path.
    return not PROTECTED_TOKEN_RE.search(text) and "\n" not in text and "\r" not in text


def make_groups(entries, batch_size, max_chars):
    """
    Build groups for the fast path. Tagged lines are isolated as single safe groups.
    Plain consecutive lines are packed up to batch_size / max_chars.
    """
    groups = []
    pending = []
    pending_chars = 0

    def flush():
        nonlocal pending, pending_chars
        if pending:
            groups.append(("plain", pending))
            pending = []
            pending_chars = 0

    for entry in entries:
        text = entry["text"]

        if not is_fast_safe(text):
            flush()
            groups.append(("protected", [entry]))
            continue

        item_chars = len(text)
        if pending and (
            len(pending) >= batch_size
            or pending_chars + item_chars > max_chars
        ):
            flush()

        pending.append(entry)
        pending_chars += item_chars

    flush()
    return groups


def find_rpy_files(path):
    return sorted(Path(path).rglob("*.rpy"))


def load_finished(path):
    if not path.exists():
        return set()
    return {
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    }


def append_finished(path, file_path):
    with path.open("a", encoding="utf-8") as f:
        f.write(str(file_path.resolve()) + "\n")


def process_file(file_path, args, model, finished_path, finished):
    resolved = str(file_path.resolve())
    if resolved in finished and not args.retranslate:
        print(f"跳过已完成：{file_path}")
        return

    original = file_path.read_text(encoding="utf-8")
    lines = original.splitlines(keepends=False)
    entries = collect_entries(lines, retranslate=args.retranslate)

    if not entries:
        print(f"无待翻译文本，跳过：{file_path}")
        if not args.retranslate and resolved not in finished:
            append_finished(finished_path, file_path)
        return

    backup_path = file_path.with_suffix(file_path.suffix + ".bak")
    if args.backup and not backup_path.exists():
        backup_path.write_text(original, encoding="utf-8")

    groups = make_groups(entries, args.batch, args.max_batch_chars)
    history = []

    for kind, group in tqdm(groups, desc=file_path.name, unit="batch"):
        if kind == "protected":
            entry = group[0]
            results = [
                translate_protected(
                    args.base_url,
                    model,
                    entry["text"],
                    args,
                    history,
                )
            ]
        else:
            results = translate_plain_batch_recursive(
                args.base_url,
                model,
                group,
                args,
                history,
            )

        for entry, translated in zip(group, results):
            escaped = encode_renpy_string(translated)
            lines[entry["line"]] = (
                f'{entry["prefix"]}"{escaped}"{entry["suffix"]}'
            )
            history.append((entry["text"], translated))

        # Keep context small. A batch already supplies local context for all its lines.
        if args.context > 0:
            history = history[-max(args.context * 2, args.context):]
        else:
            history = []

        # Incremental checkpoint so Ctrl+C/model failure doesn't lose prior groups.
        file_path.write_text(
            "\n".join(lines) + ("\n" if original.endswith("\n") else ""),
            encoding="utf-8",
        )

    if not args.retranslate:
        append_finished(finished_path, file_path)

    print(f"处理完成：{file_path}")


def parse_args():
    p = argparse.ArgumentParser(
        description="Ren'Py rpy 本地 AI 一键翻译（LM Studio / HY-MT 高速模式）"
    )
    p.add_argument(
        "path",
        help="Ren'Py 生成的翻译目录，例如 game/tl/schinese",
    )
    p.add_argument(
        "--base-url",
        default=os.getenv("LMSTUDIO_BASE_URL", DEFAULT_BASE_URL),
        help="LM Studio API，默认 http://127.0.0.1:1234/v1",
    )
    p.add_argument(
        "--model",
        default=os.getenv("LMSTUDIO_MODEL", DEFAULT_MODEL),
        help="模型 id；默认 auto 自动取 /v1/models 第一个模型",
    )
    p.add_argument("--target-language", default=DEFAULT_LANGUAGE)
    p.add_argument(
        "--batch",
        type=int,
        default=DEFAULT_BATCH,
        help="普通文本每个请求最多翻译多少行，默认 16；推荐 HY-MT 尝试 16~32",
    )
    p.add_argument(
        "--context",
        type=int,
        default=DEFAULT_CONTEXT,
        help="额外附带前文英中对照条数，默认 0（最快）；批内连续对白本身已有上下文",
    )
    p.add_argument(
        "--max-batch-chars",
        type=int,
        default=DEFAULT_MAX_BATCH_CHARS,
        help="单个批次最大原文字符数，默认 6000",
    )
    p.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT)
    p.add_argument("--retries", type=int, default=DEFAULT_RETRIES)
    p.add_argument("--temperature", type=float, default=DEFAULT_TEMPERATURE)
    p.add_argument("--top-p", type=float, default=DEFAULT_TOP_P)
    p.add_argument("--max-tokens", type=int, default=DEFAULT_MAX_TOKENS)
    p.add_argument(
        "--retranslate",
        action="store_true",
        help="重新翻译已经是中文的行；会尝试从 Ren'Py 注释/old 行恢复英文原文",
    )
    p.add_argument(
        "--no-backup",
        dest="backup",
        action="store_false",
        help="不创建 .rpy.bak 备份",
    )
    p.set_defaults(backup=True)
    return p.parse_args()


def main():
    args = parse_args()

    if args.batch < 1:
        print("--batch 必须 >= 1", file=sys.stderr)
        return 2
    if args.context < 0:
        print("--context 必须 >= 0", file=sys.stderr)
        return 2
    if args.max_batch_chars < 100:
        print("--max-batch-chars 必须 >= 100", file=sys.stderr)
        return 2

    args.base_url = normalize_base_url(args.base_url)
    root = Path(args.path)

    if not root.exists():
        print(f"目录不存在：{root}", file=sys.stderr)
        return 2

    model = detect_model(args.base_url, args.model)

    print(f"LM Studio: {args.base_url}")
    print(f"模型: {model}")
    print(f"翻译目录: {root.resolve()}")
    print(
        f"高速批量: 最多 {args.batch} 行/请求；"
        f"额外前文: {args.context} 条；"
        f"批次字符上限: {args.max_batch_chars}"
    )
    print("标签策略: 含 Ren'Py 标签/变量的行自动走安全模式，标签不会发送给模型")

    if args.retranslate:
        print("模式: 重新翻译已有中文（仅能恢复到英文原文的行）")
    else:
        print("模式: 增量翻译（已有中文保持不变）")

    finished_path = Path("finished_file_list_lmstudio.txt")
    finished = load_finished(finished_path)
    files = find_rpy_files(root)

    if not files:
        print("没有找到 .rpy 文件。")
        return 1

    for file_path in files:
        try:
            process_file(file_path, args, model, finished_path, finished)
        except KeyboardInterrupt:
            print("\n用户中止。已完成的批次已写回文件。")
            return 130
        except Exception as e:
            with Path("error_file_list_lmstudio.txt").open(
                "a", encoding="utf-8"
            ) as f:
                f.write(f"{file_path.resolve()}\t{e}\n")
            print(f"处理失败：{file_path}\n{e}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
